development:
  adapter: mysql2
  username: root
  password: coisa
  database: redu_apps_development
  host: localhost

test:
  adapter: mysql2
  username: root
  password: coisa
  database: redu_apps_test
  host: localhost