development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: reduapps_dev

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: reduapps_test

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: reduapps_prod
