development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: coisa
  database: redu_apps_development

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: coisa
  database: redu_apps_test
