User: #Tipo que vem no payload
  attributes: # Que variaveis sao usadas do hash
    - login
    - first_name
    - last_name
    - id
    - crypted_password
    - password_salt
    - email
    - persistence_token
    - client_applications
  id: core_id # Como traduzir o id
  include_data: # Data default que é adicionada
    - role: member
  name: User # Nome do modelo local

Environment:
  attributes:
    - name
    - id
    - user_id
  id: core_id
  check_for: # Checa por dependencias
    User: user_id # A chave é o modelo e o valor é como a gente procura por ele
  name: Environment

Course:
  attributes:
    - name
    - id
    - user_id
    - environment_id
  id: core_id
  check_for:
    Environment: environment_id
    User: user_id
  name: Course

Space:
  attributes:
    - name
    - id
    - course_id
  id: core_id
  check_for:
    Course: course_id
  name: Space

Subject:
  attributes:
    - name
    - id
    - space_id
  id: core_id
  check_for:
    Space: space_id
  name: Subject

UserCourseAssociation:
  attributes:
    - id
    - user_id
    - course_id
    - role
  id: core_id
  check_for:
    User: user_id
    Course: course_id
  name: UserCourseAssociation
